// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: fcb6b8a75247f603f5bb6636b1808bbd)
declare namespace Cloudflare {
	interface Env {
		DOCUMENTS_INDEX: VectorizeIndex;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
